// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package instancerepo

import (
	"database/sql/driver"
	"errors"
	"fmt"
)

const (
	// InstanceStatusCREATING is a InstanceStatus of type CREATING.
	InstanceStatusCREATING InstanceStatus = iota
	// InstanceStatusRUNNING is a InstanceStatus of type RUNNING.
	InstanceStatusRUNNING
	// InstanceStatusDELETED is a InstanceStatus of type DELETED.
	InstanceStatusDELETED
)

var ErrInvalidInstanceStatus = errors.New("not a valid InstanceStatus")

const _InstanceStatusName = "CREATINGRUNNINGDELETED"

var _InstanceStatusMap = map[InstanceStatus]string{
	InstanceStatusCREATING: _InstanceStatusName[0:8],
	InstanceStatusRUNNING:  _InstanceStatusName[8:15],
	InstanceStatusDELETED:  _InstanceStatusName[15:22],
}

// String implements the Stringer interface.
func (x InstanceStatus) String() string {
	if str, ok := _InstanceStatusMap[x]; ok {
		return str
	}
	return fmt.Sprintf("InstanceStatus(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x InstanceStatus) IsValid() bool {
	_, ok := _InstanceStatusMap[x]
	return ok
}

var _InstanceStatusValue = map[string]InstanceStatus{
	_InstanceStatusName[0:8]:   InstanceStatusCREATING,
	_InstanceStatusName[8:15]:  InstanceStatusRUNNING,
	_InstanceStatusName[15:22]: InstanceStatusDELETED,
}

// ParseInstanceStatus attempts to convert a string to a InstanceStatus.
func ParseInstanceStatus(name string) (InstanceStatus, error) {
	if x, ok := _InstanceStatusValue[name]; ok {
		return x, nil
	}
	return InstanceStatus(0), fmt.Errorf("%s is %w", name, ErrInvalidInstanceStatus)
}

// MarshalText implements the text marshaller method.
func (x InstanceStatus) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *InstanceStatus) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseInstanceStatus(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *InstanceStatus) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

var errInstanceStatusNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *InstanceStatus) Scan(value interface{}) (err error) {
	if value == nil {
		*x = InstanceStatus(0)
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case int64:
		*x = InstanceStatus(v)
	case string:
		*x, err = ParseInstanceStatus(v)
	case []byte:
		*x, err = ParseInstanceStatus(string(v))
	case InstanceStatus:
		*x = v
	case int:
		*x = InstanceStatus(v)
	case *InstanceStatus:
		if v == nil {
			return errInstanceStatusNilPtr
		}
		*x = *v
	case uint:
		*x = InstanceStatus(v)
	case uint64:
		*x = InstanceStatus(v)
	case *int:
		if v == nil {
			return errInstanceStatusNilPtr
		}
		*x = InstanceStatus(*v)
	case *int64:
		if v == nil {
			return errInstanceStatusNilPtr
		}
		*x = InstanceStatus(*v)
	case float64: // json marshals everything as a float64 if it's a number
		*x = InstanceStatus(v)
	case *float64: // json marshals everything as a float64 if it's a number
		if v == nil {
			return errInstanceStatusNilPtr
		}
		*x = InstanceStatus(*v)
	case *uint:
		if v == nil {
			return errInstanceStatusNilPtr
		}
		*x = InstanceStatus(*v)
	case *uint64:
		if v == nil {
			return errInstanceStatusNilPtr
		}
		*x = InstanceStatus(*v)
	case *string:
		if v == nil {
			return errInstanceStatusNilPtr
		}
		*x, err = ParseInstanceStatus(*v)
	}

	return
}

// Value implements the driver Valuer interface.
func (x InstanceStatus) Value() (driver.Value, error) {
	return x.String(), nil
}
